name: Build Image

on:
  pull_request: {}
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2       
    - run: chmod +x .github/workflows/scripts/build.sh
    - run: .github/workflows/scripts/build.sh
    - name: Move Output
      run: mv /home/runner/work/FullPageOS/FullPageOS/FullPageOS/src/workspace/*-raspbian-buster-lite.img /home/runner/work/FullPageOS/FullPageOS/FullPageOS/src/workspace/fullpageos.img
    - name: Zip Output
      run: gzip /home/runner/work/FullPageOS/FullPageOS/FullPageOS/src/workspace/fullpageos.img
    - uses: actions/upload-artifact@v1
      with:
        name: fullpageos.img.gz
        path: /home/runner/work/FullPageOS/FullPageOS/FullPageOS/src/workspace/fullpageos.img.gz
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
    - name: Upload Release
      id: upload-release-asset-fullpageos
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: /home/runner/work/FullPageOS/FullPageOS/FullPageOS/src/workspace/fullpageos.img.gz
        asset_name: fullpageos.img.gz
        asset_content_type: application/octet-stream