name: Build Image

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
       
    - run: |
      cd src
      docker run -v `pwd`:/distro --name mydistro_builder --device /dev/loop-control guysoft/custompios:devel