name: Build Image

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2       
    - run: chmod +x .github/workflows/scripts/build.sh
    - run: .github/workflows/scripts/build.sh